# Generated by Django 4.2.1 on 2023-05-23 22:08

from django.db import migrations, models
import django.db.models.deletion
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Última Atualiização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('activity_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=250, unique=True, verbose_name='Atividade')),
                ('mechanical_efficiency', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Eficiência Mecânia')),
                ('activity_image', pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='activity', verbose_name='Imagem')),
                ('activity_slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationsType',
            fields=[
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Última Atualiização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('operation_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type_name', models.CharField(max_length=250, unique=True, verbose_name='Tipo Operação')),
                ('operation_type_slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Última Atualiização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('operation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MAMDS_Core.activities', verbose_name='Atividades')),
                ('operation_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MAMDS_Core.operationstype', verbose_name='Tipo Operaçao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
