# Generated by Django 4.2.1 on 2023-05-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAMDS_Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='activity_slug',
            new_name='operation_slug',
        ),
    ]
